<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net472;net48</TargetFrameworks>
    <OutputType>Library</OutputType>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <AssemblyTitle>CSCore</AssemblyTitle>
    <Description>.NET Sound Library for .NET Core 8+</Description>
    <Product>CSCore-Core</Product>
    <Copyright>Jeffrey Kesselman</Copyright>
    <AssemblyVersion>1.2.1.2</AssemblyVersion>
    <FileVersion>1.2.1.2</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DefineConstants>TRACE;DEBUG;FLAC_DEBUG</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseVSHostingProcess>true</UseVSHostingProcess>
    <DocumentationFile>bin\Debug\CSCore.XML</DocumentationFile>
    <NoWarn>1573;1591</NoWarn>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DocumentationFile>bin\Release\CSCore.XML</DocumentationFile>
    <NoWarn>1591</NoWarn>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>bin\x86\Debug\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>
    </AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\license.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="AudioSubTypes.Utils.cs">
      <DependentUpon>AudioSubTypes.tt</DependentUpon>
    </Compile>
    <Compile Update="Codecs\FLAC\FlacFrame_GetBuffer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>FlacFrame_GetBuffer.tt</DependentUpon>
    </Compile>
    <Compile Update="Codecs\FLAC\SubFrames\FlacSubFrameLPC_Calculation.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>FlacSubFrameLPC_Calculation.tt</DependentUpon>
    </Compile>
    <None Update="AudioSubTypes.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>AudioSubTypes.cs</LastGenOutput>
    </None>
    <None Update="Codecs\FLAC\FlacFrame_GetBuffer.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>FlacFrame_GetBuffer.cs</LastGenOutput>
    </None>
    <None Update="Codecs\FLAC\SubFrames\FlacSubFrameLPC_Calculation.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>FlacSubFrameLPC_Calculation.cs</LastGenOutput>
    </None>
    <None Update="cscore.snk">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="System.DirectoryServices" Version="8.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.6" />
    <!--<PackageReference Include="System.Drawing.Common" Version="8.0.6" /> --> 
  </ItemGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <Reference Include="System.DirectoryServices" />
  </ItemGroup>
  <PropertyGroup>
 
  </PropertyGroup>
  <PropertyGroup>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>CSCore-Core</PackageId>
    <Title>CSCore for .NET Core</Title>
    <Version>1.0.1-beta</Version>
    <Authors>Jeffrey Kesselman</Authors>
    <Company>Purdue Polytechnic</Company>
    <PackageProjectUrl>https://github.com/profK/cscore-core</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/profK/cscore-core</RepositoryUrl>
    <PackageTags>.net;.net8;net472;net48;audio</PackageTags>
    <PackageReleaseNotes>Release Status: 1.0.1beta now can use CodecFactory to create a codec that reads its data from a provided stream.

Release Status: 1.0beta Compiling in .NET8 and seemingly working but not fully tested</PackageReleaseNotes>
    <PackageLicenseFile>license.md</PackageLicenseFile>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <AnalysisLevel>none</AnalysisLevel>
  </PropertyGroup>
  <PropertyGroup>
    <PostBuildEvent>
      @echo off &amp; setLocal EnableDELAYedeXpansion
      chcp 65001

      set errorCode=0

      set target=$(MSBuildProjectDirectory)\bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).dll
      set project=$(MSBuildProjectFullPath)

      set sdk=%25PROGRAMFILES(x86)%25\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools
      set framework=%25WINDIR%25\Microsoft.NET\Framework\v4.0.30319
      set inlineILCompiler=$(MSBuildProjectDirectory)\..\Tools\InlineILCompiler\InlineILCompiler\bin\$(Configuration)\net8.0\InlineILCompiler.exe
      set cscli=$(MSBuildProjectDirectory)\..\Tools\CSCli\bin\$(Configuration)\net8.0\CSCli.exe

      IF exist "%25sdk%25\." (
      echo OK: The Microsoft Windows SDK was found.
      ) else (
      echo FAILED: The Microsoft Windows SDK Dir was not found. Check the following path: "%25sdk%25"
      goto EXIT_ERR
      )
      IF exist "%25framework%25\." (
      echo OK: The .NET Framework Dir was found.
      ) else (
      echo FAILED: The Framework-Dir was not found. Check the following path: "%25framework%25"
      goto EXIT_ERR
      )
      IF exist "%25inlineILCompiler%25" (
      echo OK: Found the inline-il-compiler.
      ) else (
      echo FAILED: The inline-il-compiler was not found. Check the following path: "%25inlineILCompiler%25"
      goto EXIT_ERR
      )
      IF exist "%25cscli%25" (
      echo OK: Found the cscli-compiler.
      ) else (
      echo FAILED: The cscli was not found. Check the following path: "%25cscli%25"
      goto EXIT_ERR
      )

      if $(Configuration) == Debug (
      echo Build-Configuration: DEBUG
      echo    DEBUG=IMPL
      echo    NO OPTIMIZE
      set ilasm_args=/DLL /DEBUG=IMPL
      ) else (
      if $(Configuration) == Release (
      echo Build-Configuration: RELEASE
      echo    NO DEBUG
      echo    OPTIMIZE
      set ilasm_args=/DLL /OPTIMIZE
      ) else (
      echo FAILED: Invalid Configuration.
      goto EXIT_ERR
      )
      )

      echo.
      echo.
      echo Calling the inline-il-compiler ...
      call "%25inlineILCompiler%25"

      echo.
      echo.
      echo Calling CSCli ...
      call "%25cscli%25" -file:"%25target%25" -r:"RemoveObjAttribute" -c:"CSCalliAttribute"

      :EXIT
      EXIT /B %25errorCode%25

      :EXIT_ERR
      set errorCode=-1
      goto EXIT
</PostBuildEvent>
  </PropertyGroup>
</Project>